//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.27 at 04:57:42 PM IST 
//


package com.talentica.hungryHippos.sharding.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for input complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="input">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data-description" type="{http://www.talentica.com/sharding-config}data-description"/>
 *         &lt;element name="data-parser-config" type="{http://www.talentica.com/sharding-config}data-parser-config"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "input", propOrder = {
    "dataDescription",
    "dataParserConfig"
})
public class Input {

    @XmlElement(name = "data-description", required = true)
    protected DataDescription dataDescription;
    @XmlElement(name = "data-parser-config", required = true)
    protected DataParserConfig dataParserConfig;

    /**
     * Gets the value of the dataDescription property.
     * 
     * @return
     *     possible object is
     *     {@link DataDescription }
     *     
     */
    public DataDescription getDataDescription() {
        return dataDescription;
    }

    /**
     * Sets the value of the dataDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataDescription }
     *     
     */
    public void setDataDescription(DataDescription value) {
        this.dataDescription = value;
    }

    /**
     * Gets the value of the dataParserConfig property.
     * 
     * @return
     *     possible object is
     *     {@link DataParserConfig }
     *     
     */
    public DataParserConfig getDataParserConfig() {
        return dataParserConfig;
    }

    /**
     * Sets the value of the dataParserConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataParserConfig }
     *     
     */
    public void setDataParserConfig(DataParserConfig value) {
        this.dataParserConfig = value;
    }

}
